### ISSUE TITLE
Contributing Guide?

### ISSUE THREAD

**Issue by jalcine** [larroy/uvpp#5]
I really want to help out to make this a full-fledged C++11 wrapper for libuv but I'm not sure what would be the critiera for contributing. I even use a different C++ formatting style. I noticed the following:

 + 4 spaces for indenting
 + [K&R](astyle.sourceforge.net/astyle.html#_style=kr) style formatting

**Comment by larroy** [comment]
Thanks, sorry for the late followup as I didn't see this before, K&R?

As long as the style is similar shouldn't be any problems.

**Comment by jalcine** [comment]
Noted! I'll do my best to make it work. Thanks.
